language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: 78643032a0255c790feba26b1b4217c7
  app: viewing-party-and-chill
  run: rails db:migrate
on:
  repo: khoifishpond/viewing_party
  branch: main
